# Made using xcodegen 2.17.0

name: FBSDKCoreKit_Basics

options:
  deploymentTarget:
    iOS: "9.0"
  usesTabs: false
  tabWidth: 2
  indentWidth: 2
  defaultConfig: Debug

attributes:
  ORGANIZATIONNAME: Facebook

configFiles:
  Debug: Configurations/Shared/Configuration/Debug.xcconfig
  Release: Configurations/Shared/Configuration/Release.xcconfig

settings:
  base:
    # Some iOS defaults will be overridden by Xcodegen.
    # We need to explicitly set them to maintain parity with
    # the project file being replaced
    CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: false
    SWIFT_OPTIMIZATION_LEVEL: -O
    PRODUCT_NAME: FBSDKCoreKit_Basics

targets:
  FBSDKCoreKit_Basics:
    type: framework
    platform: [iOS]
    platformSuffix: ""
    sources:
      - ../Sources/FBSDKCoreKit_Basics
    configFiles:
      Debug: Configurations/FBSDKCoreKit_Basics.xcconfig
      Release: Configurations/FBSDKCoreKit_Basics.xcconfig
  FBSDKCoreKit_Basics-Dynamic:
    type: framework
    dependencies:
      - sdk: UIKit.framework
      - sdk: libz.tbd
    platform: [iOS]
    platformSuffix: ""
    sources:
      - ../Sources/FBSDKCoreKit_Basics
    configFiles:
      Debug: Configurations/FBSDKCoreKit_Basics-Dynamic.xcconfig
      Release: Configurations/FBSDKCoreKit_Basics-Dynamic.xcconfig
    settings:
      PRODUCT_NAME: FBSDKCoreKit_Basics
  FBSDKCoreKit_Basics_TV:
    type: framework
    platform: [tvOS]
    platformSuffix: ""
    sources:
      - ../Sources/FBSDKCoreKit_Basics
    configFiles:
      Debug: Configurations/FBSDKCoreKit_Basics-tvOS.xcconfig
      Release: Configurations/FBSDKCoreKit_Basics-tvOS.xcconfig
    settings:
      PRODUCT_NAME: FBSDKCoreKit_Basics
  FBSDKCoreKit_Basics_TV-Dynamic:
    type: framework
    dependencies:
      - sdk: UIKit.framework
      - sdk: libz.tbd
    platform: [tvOS]
    platformSuffix: ""
    sources:
      - ../Sources/FBSDKCoreKit_Basics
    configFiles:
      Debug: Configurations/FBSDKCoreKit_Basics-tvOS-Dynamic.xcconfig
      Release: Configurations/FBSDKCoreKit_Basics-tvOS-Dynamic.xcconfig
    settings:
      PRODUCT_NAME: FBSDKCoreKit_Basics
  FBSDKCoreKit_BasicsTests:
    type: bundle.unit-test
    platform: [iOS]
    platformSuffix: ""
    sources:
      - FBSDKCoreKit_BasicsTests
    configFiles:
      Debug: Configurations/FBSDKCoreKit_BasicsTests.xcconfig
      Release: Configurations/FBSDKCoreKit_BasicsTests.xcconfig
    dependencies:
      - target: FBSDKCoreKit_Basics-Dynamic

aggregateTargets:
  FBSDKCoreKit_Basics-Universal:
    targets: [FBSDKCoreKit_Basics]
    configFiles:
      Debug: Configurations/FBSDKCoreKit_Basics.xcconfig
      Release: Configurations/FBSDKCoreKit_Basics.xcconfig
    buildScripts:
      - name: ShellScript
        path: ../scripts/xcode/build-universal-framework.sh
  FBSDKCoreKit_Basics_TV-Universal:
    targets: [FBSDKCoreKit_Basics_TV]
    configFiles:
      Debug: Configurations/FBSDKCoreKit_Basics-tvOS.xcconfig
      Release: Configurations/FBSDKCoreKit_Basics-tvOS.xcconfig
    buildScripts:
      - name: ShellScript
        path: ../scripts/xcode/build-universal-tvos-framework.sh

schemes:
  BuildCoreKitBasics:
    build:
      targets:
        FBSDKCoreKit_Basics-Universal: [archive, run, profile, analyze]
        FBSDKCoreKit_Basics_TV-Universal: [archive, run, profile, analyze]
      parallelizeBuild: false
  FBSDKCoreKit_Basics-Dynamic:
    build:
      targets:
        FBSDKCoreKit_Basics-Dynamic: all
    test:
      targets: [FBSDKCoreKit_BasicsTests]
      coverageTargets:
        - FBSDKCoreKit_Basics-Dynamic
  FBSDKCoreKit_Basics_TV-Dynamic:
    build:
      targets:
        FBSDKCoreKit_Basics_TV-Dynamic: all
